# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan Pablo
title: Systems assistant 
email: juanpab339@gmail.com
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Juanpab84339609
github_username:  juanpa33rs
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: Juan pablo RS
# flickr_username: jekyll
instagram_username: juanpa_rs_
linkedin_username: Juan Pablo Ramirez Sandoval 
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: juanpabloramirezsandoval8048
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Juan Pablo i am systems assistant. i have worked in several companies acquiring teamwork and leadership skills i know the systems whit which most companies work i help solve day to day problems.

  I am skilled in: <mark>playing sports</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super  project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This  was a cool project that I worked on was fun.
        description: | # this will include new lines to allow paragraphs
          I started this project in my work since the infrastructure of the systems was very old. So we took on the task of changing all this completely we improved the safety optimism of the systems and replaced the unusable materials.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: constructa
        link: constructa.com
        # link_text: constructa.com
        sub_title: Systems assistant
        caption: october 2022 - Present
        quote: >
          Repairing problems on the infrastructure of your networks and operating systems.
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks to be well managed and constructa is no exception. My duties were to solve problems with Internet and intranet connections as well as solve problems that arose with the programs used to perform day to day tasks.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Guadalajara of University
        caption: 2022 - 2026
        sub_title: Computer Engineering
        quote: >
          The University of Guadalajara UDG is a public institution of secondary and higher education that has its headquarters in the Metropolitan Area of Guadalajara. Chronologically, according to its foundation, it is the second oldest university in Mexico, the seventh in North America and the fourteenth in Latin America.

        description: | # this will include new lines to allow paragraphs
          During my time at univercity of Guadalajara I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I during my stay at the University of Guadalajara I spend my time in the school gym and practicing soccer.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Run
      - Drive
      - Walking
      - Sports 
     

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
